# Editor build failure reporter
# ========================================================
#
# [Required secrets]
#   GH_WORKFLOW_TOKEN:  Github parsonal access token to dispatch workflow
name: "Build Editor Failed :x:"

env:
  # ================ Repository settings ================
  ISSUE_NUMBER: 19

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag that failed to build"
        required: true
        default: "2017.4.30f1-webgl-1.0.0"

jobs:
  comment:
    name: Comment for the image tag '${{ github.event.inputs.imageTag }}'
    runs-on: ubuntu-latest
    outputs:
      already-commented: ${{ steps.fc.outputs.comment-id != '' }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          body-includes: ${{ github.event.inputs.imageTag }}

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          body: |
            The build '${{ github.event.inputs.imageTag }}' failed.
            If it fails again, it will be added to the ignore list.

  ignore:
    name: Ignore the image tag '${{ github.event.inputs.imageTag }}' for workflow
    needs: comment
    if: needs.comment.outputs.already-commented
    runs-on: ubuntu-latest
    steps:

      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        id: co
        continue-on-error: true
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          ref: ignored-tags
      - uses: actions/checkout@v2
        if: steps.co.outcome == 'failure'

      ###########################
      # Add The Tag To Workflow #
      ###########################
      - run: |
          if [ -z "$(cat .github/workflows/build-all.yml | grep ${{ github.event.inputs.imageTag }} )" ] ;then
            sed -i -e "s/<<AUTO_IGNORED_IMAGE_TAGS>>/&\\n    ${{ github.event.inputs.imageTag }}/" .github/workflows/build-all.yml
          fi

      ###########################
      #     Create/Update PR    #
      ###########################
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          commit-message: Ignore ${{ github.event.inputs.imageTag }}
          branch: ignored-tags
          delete-branch: true
          title: Ignore tags
          labels: |
            ignored tags
          base: main
