name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/test.yml"
      - "reference-project/**"
  pull_request:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/test.yml"
      - "reference-project/**"
  schedule:
    - cron: "0 0 * * 0" # weekly

env:
  MINIMUM_VERSION: "2021.3"

jobs:
  ###########################
  #    Build base and hub   #
  ###########################
  base-and-hub:
    name: Base and hub
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.setup.outputs.versions }}
      excludes: ${{ steps.setup.outputs.excludes }}
    steps:
      ###########################
      #          Setup          #
      ###########################
      - uses: actions/checkout@v4
      - run: cat .env | sed 's/=\" *$/<<EOD/g' | sed 's/^\"/EOD/g' | grep '^[^# ]' >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      ###########################
      #   Build base and hub    #
      ###########################
      - name: Build base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: base/Dockerfile
          build-args: |
            ubuntuImage=${{ env.UBUNTU_IMAGE }}
          tags: base:dev
      - name: Build hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: hub/Dockerfile
          build-args: baseImage=base:dev
          tags: hub:dev

      ###########################
      #   Save images for next  #
      ###########################
      - name: Save images for next
        run: |
          docker images
          docker save -o base-and-hub.tar base:dev hub:dev
      - uses: actions/upload-artifact@v4
        with:
          path: base-and-hub.tar
          retention-days: 1

      ###########################
      #    Setup build matrix   #
      ###########################
      - name: "Setup build matrix"
        id: setup
        run: |
          # Get the Unity versions for test. (The latest patch versions for each minor version.)
          [ "${{ env.INCLUDE_BETA_VERSIONS }}" = 'true' ] && OPT='--all' || OPT=''
          VERSIONS=`npx unity-changeset list --versions --json --min ${{ env.MINIMUM_VERSION }} --latest-patch ${OPT}`
          echo "Versions: $VERSIONS"
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT

          # Exclude linux-il2cpp for Unity 2019.2 or earlier
          EXCLUDES="$EXCLUDES `echo \"$VERSIONS\" | jq -c '[ .[] | select(test(\"2018|2019.1|2019.2\")) | { version: ., module: \"linux-il2cpp\"} ]'`"

          EXCLUDES=`echo "$EXCLUDES" | jq -s -c 'flatten'`
          echo "Excludes: $EXCLUDES"
          echo "excludes=$EXCLUDES" >> $GITHUB_OUTPUT

  ###########################
  #  Build editor and test  #
  ###########################
  editor:
    needs: base-and-hub
    name: Editor (${{ matrix.version }}-${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        # The latest patch versions for each minor version.
        version: ${{ fromJson(needs.base-and-hub.outputs.versions) }}
        module:
          - base
          - linux-il2cpp
          - windows-mono
          - mac-mono
          - ios
          - android
          - webgl
        include:
          - module: base
            platform: StandaloneLinux64
          - module: linux-il2cpp
            platform: StandaloneLinux64
          - module: windows-mono
            platform: StandaloneWindows
          - module: mac-mono
            platform: StandaloneOSX
          - module: ios
            platform: iOS
          - module: android
            platform: Android
          - module: webgl
            platform: WebGL
        exclude: ${{ fromJson(needs.base-and-hub.outputs.excludes) }}

    steps:
      ###########################
      #          Setup          #
      ###########################
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Free disk space
        run: .github/workflows/scripts/free_disk_space.sh

      ###########################
      #   Restore base and hub  #
      ###########################
      - uses: actions/download-artifact@v4
      - name: Restore base and hub
        run: |
          docker load -i artifact/base-and-hub.tar
          rm -rf artifact

      ###########################
      #      Setup to build     #
      ###########################
      - name: Setup to build
        run: |
          # The changeset for unity version
          echo "CHANGESET=`npx unity-changeset ${{ matrix.version }}`" >> $GITHUB_ENV

          # For 2019.3 or later, non-il2cpp would also be possible to build with il2cpp image.
          if [ `echo "${{ matrix.version }}" | grep -v '\(2018\|2019.1\|2019.2\)'` ] && [ "${{ matrix.module }}" = 'base' ] ; then
            echo "MODULE=linux-il2cpp" >> $GITHUB_ENV
          else
            echo "MODULE=${{ matrix.module }}" >> $GITHUB_ENV
          fi

      ###########################
      #       Build editor      #
      ###########################
      - name: Build
        # if: steps.build-1.outcome == 'failure'
        uses: docker/build-push-action@v5
        id: build-1
        continue-on-error: true
        timeout-minutes: 40
        with:
          context: .
          file: editor/Dockerfile
          build-args: |
            baseImage=base:dev
            hubImage=hub:dev
            version=${{ matrix.version }}
            changeSet=${{ env.CHANGESET }}
            module=${{ env.MODULE }}
          tags: editor:dev

      ###########################
      #   Build editor (retry)  #
      ###########################
      - name: Sleep for retry
        if: steps.build-1.outcome == 'failure'
        run: sleep 120

      - name: Build (Retry)
        if: steps.build-1.outcome == 'failure'
        uses: docker/build-push-action@v5
        id: build-2
        # continue-on-error: true
        timeout-minutes: 40
        with:
          context: .
          file: editor/Dockerfile
          build-args: |
            baseImage=base:dev
            hubImage=hub:dev
            version=${{ matrix.version }}
            changeSet=${{ env.CHANGESET }}
            module=${{ env.MODULE }}
          tags: editor:dev

      ###########################
      #      Setup to test      #
      ###########################
      - name: Show image size
        run: docker images
      - name: Setup to test
        run: |
          # For 'linux-il2cpp' module, switch the script backend to 'IL2CPP'
          if [ "${{ matrix.module }}" = "linux-il2cpp" ] ; then
            mv -f reference-project/ProjectSettings/ProjectSettings_il2cpp.asset reference-project/ProjectSettings/ProjectSettings.asset
          fi

      ###########################
      #          Build          #
      ###########################
      - name: Build project
        uses: game-ci/unity-builder@main
        timeout-minutes: 35
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.version }}
          customImage: editor:dev
          projectPath: reference-project
          targetPlatform: ${{ matrix.platform }}
          allowDirtyBuild: true
          customParameters: -nographics

      ###########################
      #       Build (GZip)      #
      ###########################
      - name: "⚙️ Setup (GZip)"
        if: env.MODULE == 'webgl'
        run: |
          # Set WebGL compression format to gzip
          sed -i -e 's/webGLCompressionFormat: .*$/webGLCompressionFormat: 1/' reference-project/ProjectSettings/ProjectSettings.asset
      - name: Build project (GZip)
        if: env.MODULE == 'webgl'
        uses: game-ci/unity-builder@main
        timeout-minutes: 35
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.version }}
          customImage: editor:dev
          projectPath: reference-project
          targetPlatform: ${{ matrix.platform }}
          allowDirtyBuild: true
          customParameters: -nographics

      ###########################
      #       Build (Brotli)      #
      ###########################
      - name: "⚙️ Setup (Brotli)"
        if: env.MODULE == 'webgl'
        run: |
          # Set WebGL compression format to brotli
          sed -i -e 's/webGLCompressionFormat: .*$/webGLCompressionFormat: 0/' reference-project/ProjectSettings/ProjectSettings.asset
      - name: Build project (Brotli)
        if: env.MODULE == 'webgl'
        uses: game-ci/unity-builder@main
        timeout-minutes: 35
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.version }}
          customImage: editor:dev
          projectPath: reference-project
          targetPlatform: ${{ matrix.platform }}
          allowDirtyBuild: true
          customParameters: -nographics

      ###########################
      #           Test          #
      ###########################
      - name: Test project
        uses: game-ci/unity-test-runner@main
        timeout-minutes: 35
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.version }}
          customImage: editor:dev
          projectPath: reference-project
          customParameters: -nographics -buildTarget ${{ matrix.platform }}

      ###########################
      # Validate Android Utils  #
      ###########################
      - name: Validate Android Utils
        if: env.MODULE == 'android'
        uses: addnab/docker-run-action@v3
        with:
          image: editor:dev
          run: bash -l -c 'java -version && sdkmanager --version && cat $ANDROID_NDK_HOME/source.properties'
